
image: node:10.15.3

pipelines: 
  branches:
    master:
    - step:
        name: Generate Static Files
        caches:
          - node
          - composer
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/*
          - dist/**/*
          - dist/**/**
