
image: node:10.15.3

pipelines: 
  custom:
    deploy-to-prod:
     - step:
        name: Generate Static Files
        caches:
          - node
          - composer
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**
     - step:
        name: Deploy to Production
        deployment: Production
        script:
          - apt-get update
          - apt-get install ncftp
          - ncftpput -v -u "$FTP_USERNAME" -p "$FTP_PASSWORD" -R $FTP_HOST . dist/*
  branches:
    master:
     - step:
        name: Generate Static Files
        caches:
          - node
          - composer
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**    
     - step:
          name: Deploy to DEV
          deployment: Development
          script:
            - apt-get update            
            - apt-get install lftp
            - lftp -u $FTP_USERNAME,$FTP_PASSWORD -e "set ftp:ssl-allow no; mirror --delete -vvv -R dist/* dev;quit" $FTP_HOST
            