
image: node:10.15.3

pipelines: 
  custom:
    deploy-to-prod:
     - step:
        name: Generate Static Files
        caches:
          - node
          - composer
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**
     - step:
        name: Deploy to Production
        deployment: Production
        script:
          - apt-get update
          - apt-get install ncftp
          - ncftpput -v -u "$FTP_USERNAME" -p "$FTP_PASSWORD" -R $FTP_HOST . dist/*
  branches:
    master:
     - step:
        name: Generate Static Files
        caches:
          - node
          - composer
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**    
     - step:
          name: Deploy to DEV
          deployment: Development
          script:
            - apt-get update
            - apt-get install ncftp
            - apt-get install lftp
            - lftp -e "open $FTP_HOST; user $FTP_USERNAME,$FTP_PASSWORD; mirror --reverse --delete dev/"
            - ncftpput -v -u "$FTP_USERNAME" -p "$FTP_PASSWORD" -R $FTP_HOST dev dist/*